import 'package:get/get.dart';

class LocaleString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    //ENGLISH LANGUAGE
    'en_US':{
      'Good Morning':'Good Morning',
      'Good Afternoon':'Good Afternoon',
      'Good Evening':'Good Evening',
      'Good Night':'Good Night',
      'Diabetes':'Diabetes',
      'Blood Pressure (BP)':'Blood Pressure (BP)',
      'After Meal':'After Meal',
      'Before Meal':'Before Meal',
      'Diabetes History':'Diabetes History',
      'Item delete successfully':'Item delete successfully',
      'Add Diabetes':'Add Diabetes',
      'Select Time':'Select Time',
      'Cencel':'Cencel',
      'Ok':'Ok',
      'Date':'Date',
      'Time':'Time',
      'Enter the value':'Enter the value',
      'Value':'Value',
      'Delete':'Delete',
      'Save':'Save',
      'Select the After or Before':'Select the After or Before',
      'Information':'Information',
      'Diabetes Control Level':'Diabetes Control Level',
      'Blood Pressure Control Level':'Blood Pressure Control Level',
      'Add Blood Pressure':'Add Blood Pressure',
      'Lower value':'Lower value',
      'Enter the Lower value':'Enter the Lower value',
      'Upper value':'Upper value',
      'Enter the Upper value':'Enter the Upper value',
      'Oops!':'Oops!',
      "We couldn't find any data to show":"We couldn't find any data to show",
      "Blood Pressure":'Blood Pressure',
    },
    //HINDI LANGUAGE
    'hi_IN':{
      'Good Morning':'शुभ प्रभात',
      'Good Afternoon':'शुभ दोपहर',
      'Good Evening':'शुभ संध्या',
      'Good Night':'शुभ रात्रि',
      'Diabetes':'मधुमेह',
      'Blood Pressure (BP)':'रक्तचाप (बीपी)',
      'After Meal':'भोजन के बाद',
      'Before Meal':'भोजन से पहले',
      'Diabetes History':'मधुमेह का इतिहास',
      'Item delete successfully':'आइटम सफलतापूर्वक हटा दिया गया',
      'Add Diabetes':'मधुमेह जोड़ें',
      'Select Time':'समय चुनें',
      'Cencel':'नहीं',
      'Ok':'ठीक',
      'Date':'तारीख',
      'Time':'समय',
      'Enter the value':'मान प्रविष्ट करें',
      'Value':'मूल्य',
      'Delete':'मिटाना',
      'Save':'बचायें',
      'Select the After or Before':'बाद या उससे पहले का चयन करें',
      'Information':'जानकारी',
      'Diabetes Control Level':'मधुमेह नियंत्रण स्तर',
      'Blood Pressure Control Level':'रक्तचाप नियंत्रण स्तर',
      'Add Blood Pressure':'रक्तचाप जोड़ें',
      'Lower value':'कम मूल्य',
      'Enter the Lower value':'निचला मूल्य दर्ज करें',
      'Upper value':'ऊपरी मूल्य',
      'Enter the Upper value':'ऊपरी मूल्य दर्ज करें',
      'Oops!':'उफ़!',
      "We couldn't find any data to show":"हमें दिखाने के लिए कोई डेटा नहीं मिला",
      "Blood Pressure":'रक्तचाप'
    },
    //GUJARATI LANGUAGE
    'gu_IN':{
      'Good Morning':'સુપ્રભાત',
      'Good Afternoon':'શુભ બપોર',
      'Good Evening':'શુભ સાંજ',
      'Good Night':'શુભ રાત્રી',
      'Diabetes':'ડાયાબીટીસ',
      'Blood Pressure (BP)':'બ્લડ પ્રેશર (બીપી)',
      'After Meal':'ભોજન પછી',
      'Before Meal':'ભોજન પહેલાં',
      'Diabetes History':'ડાયાબિટીસ વિગત',
      'Item delete successfully':'આઇટમ સફળતાપૂર્વક કાઢી નાખી',
      'Add Diabetes':'ડાયાબિટીસ ઉમેરો',
      'Select Time':'સમય પસંદ કરો',
      'Cencel':'નહિ',
      'Ok':'બરાબર',
      'Date':'તારીખ',
      'Time':'સમય',
      'Enter the value':'મૂલ્ય દાખલ કરો',
      'Value':'મૂલ્ય',
      'Delete':'કાઢી નાખો',
      'Save':'સાચવો',
      'Select the After or Before':'પછી અથવા પહેલા પસંદ કરો',
      'Information':'માહિતી',
      'Diabetes Control Level':'ડાયાબિટીસ નિયંત્રણ સ્તર',
      'Blood Pressure Control Level':'બ્લડ પ્રેશર નિયંત્રણ સ્તર',
      'Add Blood Pressure':'બ્લડ પ્રેશર ઉમેરો',
      'Lower value':'નીચું મૂલ્ય',
      'Enter the Lower value':'નીચલા મૂલ્ય દાખલ કરો',
      'Upper value':'ઉપલા મૂલ્ય',
      'Enter the Upper value':'ઉચ્ચ મૂલ્ય દાખલ કરો',
      'Oops!':'અરેરે!',
      "We couldn't find any data to show":"અમે બતાવવા માટે કોઈ ડેટા શોધી શક્યા નથી",
      'Blood Pressure':'બ્લડ પ્રેશર'
    }
  };

}